--- 
services: 
  python_tests_docker: 
    volumes:
      - /dev/urandom:/dev/random
    environment: 
      HUB_URL: http://${HUB_URL}:4444/wd/hub
    image: "python-tests-docker"
    shm_size: 2G
version: "3.8"
